apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr-app
  template:
    metadata:
      labels:
        app: hr-app
    spec:
      containers:
        - name: hr-app
          image: afnanyousuf/secondapp:latest # or hr-app:v1 if using minikube load
          ports:
            - containerPort: 3000