name: Deploy HR App to Kubernetes
on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/secondapp:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/secondapp:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.27.0

      - name: Configure Kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml

      - name: Update Kubernetes Deployment
        run: |
          kubectl --kubeconfig=kubeconfig.yaml \
          set image deployment/hr-app-deployment \
          hr-app=${{ secrets.DOCKER_USERNAME }}/secondapp:latest
